<?php
            $status = Mage::getStoreConfig('facebook_option/facebooklike/status');
            $facebookUrl = Mage::getStoreConfig('facebook_option/facebooklike/facebook_url');
?>
<?php if($status==1){ ?>
<aside id="meta" class="widget">
<div id="fb-root"></div>
<script>(function(d, s, id) {
var js, fjs = d.getElementsByTagName(s)[0];
if (d.getElementById(id)) return;
js = d.createElement(s); js.id = id;
js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="fb-like-box" data-href="<?php echo $facebookUrl; ?>" data-width="200" data-height="315" data-show-faces="true" data-stream="false" data-header="false"></div>
</aside>
<?php } ?>
